"""init all tables

Revision ID: ba9f71c0dabe
Revises: 
Create Date: 2026-09-14 17:05:14.784347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9f71c0dabe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotent_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idem_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idempotent_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotent_record_idem_key'), ['idem_key'], unique=True)

    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('encrypt_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('encrypted_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('queue', sa.String(length=20), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encrypt_task', schema=None) as batch_op:
        batch_op.create_index('idx_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_encrypt_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_encrypt_task_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_encrypt_task_user_id'), ['user_id'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_no', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index('idx_report_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_report_no'), ['report_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_report_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_user_id'), ['user_id'], unique=False)

    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('report_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_version', schema=None) as batch_op:
        batch_op.create_index('idx_report_version', ['report_id', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_version_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_version_report_id'))
        batch_op.drop_index('idx_report_version')

    op.drop_table('report_version')
    op.drop_table('user_role')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_user_id'))
        batch_op.drop_index(batch_op.f('ix_report_status'))
        batch_op.drop_index(batch_op.f('ix_report_report_no'))
        batch_op.drop_index('idx_report_user_status')

    op.drop_table('report')
    with op.batch_alter_table('encrypt_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encrypt_task_user_id'))
        batch_op.drop_index(batch_op.f('ix_encrypt_task_task_id'))
        batch_op.drop_index(batch_op.f('ix_encrypt_task_status'))
        batch_op.drop_index('idx_user_status')

    op.drop_table('encrypt_task')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('role')
    with op.batch_alter_table('idempotent_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotent_record_idem_key'))

    op.drop_table('idempotent_record')
    # ### end Alembic commands ###
